export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const FETCH_RANDOM_TEXT_SUCCESS = "FETCH_RANDOM_TEXT_SUCCESS";
export const RANDOM_TEXT_FETCH_REQUESTED = "RANDOM_TEXT_FETCH_REQUESTED";